# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: osx
  pool:
    vmImage: macOS-10.15
  strategy:
    matrix:
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpimpichpython3.6.____73_pypy:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpimpichpython3.6.____73_pypy
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpimpichpython3.6.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpimpichpython3.6.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpimpichpython3.7.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpimpichpython3.7.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpimpichpython3.8.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpimpichpython3.8.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpimpichpython3.9.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpimpichpython3.9.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpiopenmpipython3.6.____73_pypy:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpiopenmpipython3.6.____73_pypy
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpiopenmpipython3.6.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpiopenmpipython3.6.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpiopenmpipython3.7.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpiopenmpipython3.7.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpiopenmpipython3.8.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpiopenmpipython3.8.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpiopenmpipython3.9.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version7mpiopenmpipython3.9.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpimpichpython3.6.____73_pypy:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpimpichpython3.6.____73_pypy
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpimpichpython3.6.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpimpichpython3.6.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpimpichpython3.7.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpimpichpython3.7.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpimpichpython3.8.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpimpichpython3.8.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpimpichpython3.9.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpimpichpython3.9.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpiopenmpipython3.6.____73_pypy:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpiopenmpipython3.6.____73_pypy
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpiopenmpipython3.6.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpiopenmpipython3.6.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpiopenmpipython3.7.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpiopenmpipython3.7.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpiopenmpipython3.8.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpiopenmpipython3.8.____cpython
        UPLOAD_PACKAGES: 'True'
      osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpiopenmpipython3.9.____cpython:
        CONFIG: osx_64_c_compiler_version10cxx_compiler_version10fortran_compiler_version9mpiopenmpipython3.9.____cpython
        UPLOAD_PACKAGES: 'True'
  timeoutInMinutes: 360

  steps:
  # TODO: Fast finish on azure pipelines?
  - script: |
      export CI=azure
      export OSX_FORCE_SDK_DOWNLOAD="1"
      export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
      export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
      ./.scripts/run_osx_build.sh
    displayName: Run OSX build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)
      FEEDSTOCK_TOKEN: $(FEEDSTOCK_TOKEN)
      STAGING_BINSTAR_TOKEN: $(STAGING_BINSTAR_TOKEN)